# ANÁLISIS Y ESTANDARIZACIÓN DE MARCAS

In [1]:
import sys
import os
project_root = os.path.dirname(os.getcwd()) 
sys.path.insert(0, project_root)
from utils.imports import *

==================================================
VERSIONES DE LIBRERÍAS
==================================================
Python: 3.10.19
pandas: 2.3.3
numpy: 2.2.6
matplotlib: 3.10.0
seaborn: 0.13.2
Pandas: 2.3.3
IPython: 8.38.0

## PRODUCTOS DE ODOO

In [2]:
notebook_dir = os.path.dirname(os.path.abspath('__file__'))
data_odoo_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'ProductosOdoo.csv')
df_odoo = pd.read_csv(data_odoo_path)
print(f"Total productos: {len(df_odoo)}")
print(f"Columnas: {list(df_odoo.columns)}")
df_odoo.head(5)

Total productos: 14215
Columnas: ['id', 'name', 'barcode', 'default_code', 'x_studio_many2many_field_37q_1irl4uc58', 'categ_id', 'seller_ids']

,id,name,barcode,default_code,x_studio_many2many_field_37q_1irl4uc58,categ_id,seller_ids
0,__export__.product_template_31022_88373f19,ADORNO HALLOWEN,7453066213137,CF00614/autoriza noris,NaN,Cumpleaños / Artículos de Fiesta,NaN
1,__export__.product_template_219315_4256fd8c,ARCHIVADOR VERTICAL 3 GAVETAS Y CERRADURA,NaN,NaN,NaN,All,NaN
2,__export__.product_template_219316_dfced89f,ARCHIVADOR VERTICAL 4 GAVETAS Y CERRADURA,NaN,NaN,NaN,All,NaN
3,__export__.product_template_76612_602c2239,ARTICULOS DE NAVIDAD,93,9,NaN,Navidad / Bolas,NaN
4,__export__.product_template_29991_44f2fe53,ARTICULOS FIESTA,17,1,NaN,Cumpleaños / Artículos de Fiesta,NaN

## PRODUCTOS DE INTERFUERZA

In [3]:
data_inter_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'ProductosInterfuerza.xlsx')
df_int = pd.read_excel(data_inter_path)
print(f"Total productos: {len(df_int)}")
print(f"Columnas: {list(df_int.columns)}")
df_int.head(5)

Total productos: 73681
Columnas: ['Id', 'UPC Code', 'Ubicacion', 'Item Number', 'Tipo', 'Nombre', 'Proveedor Principal', 'Marca', 'Pais de Origen', 'Punto de ReOrden', 'Ultimo Precio Proveedor', 'InStock', 'Costo Promedio', 'Precio de Lista Predeterminada', 'Costo Promedio WH', 'Ultimo Precio Proveedor Purchase', 'Ultimo Costo Entrada', 'Ultimo Costo Unitario F', 'Ultimo Costo Unitario', 'Margen ', 'Creacion', 'Actualizado', 'Categoria L1', 'Categoria L2', 'Categoria L3', 'Agente', 'Status', 'Cuenta de Venta', 'Cuenta Costo', 'Cuenta de Inventario', 'Imagen', 'Comision', 'Grosor', 'Ancho', 'Altura', 'Largo', 'Impuesto', 'Lote', 'Expiracion', 'Color', 'Talla', 'Temporada', 'Prod Madre', 'Matriz Padre', 'Matriz Hijo', 'Arancel', 'Material', 'UoM InStock', 'UoM Compra', 'UoM Venta', 'Tags', 'Peso', 'Detalle']

,Id,UPC Code,Ubicacion,Item Number,Tipo,Nombre,Proveedor Principal,Marca,Pais de Origen,Punto de ReOrden,...,Matriz Padre,Matriz Hijo,Arancel,Material,UoM InStock,UoM Compra,UoM Venta,Tags,Peso,Detalle
0,PRO101109,7512155423106,BODEGA PRINCIPAL,A404/6917,PRODUCTO,GORRA FBI 7512155423106,OMER SA,GENERICO,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,SOMBRERO SHERIFF
1,PRO104891,40568000067,NaN,405686/25.95OFERTA5.00,PRODUCTO,VESTIDO LARGO DAMA CHINO,CAPI WORLDWIDE SA,ZZZZZ,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,VESTIDO LARGO DAMA CHINO
2,PRO107818,7465376497664,NaN,9599/HB2473-18,PRODUCTO,BIRRETE GRADUACION NEGRO-AZUL TELA 7465376497664,OMER SA,GENERICO,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,VIRRETE GRADUACION TELA
3,PRO107822,6930180607994,NaN,AFD-799,PRODUCTO,NUMEROS LED CHICO AFD-799,SOLARTE DE PANAMA SA,FIESTAS DAISY,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NUMEROS LED CHICO AFD-799
4,PRO107852,60000001438,BODEGA PRINCIPAL,601430,PRODUCTO,ARREGLO GRADUACION GLOBOS,CORPORACION DAISY SA,DAISY,NaN,0,...,NO,NO,NaN,NaN,NaN,NaN,NaN,NaN,0.0,ARREGLO GRADUACION GLOBOS

## ANÁLISIS DE PRODUCTOS SIN MARCAS

In [94]:
df_copy = df_odoo.copy()
# Productos nulos o vacíos
df_null = df_copy['x_studio_many2many_field_37q_1irl4uc58'].isna()
df_whitespace = df_copy['x_studio_many2many_field_37q_1irl4uc58'].astype(str).str.contains(r'^\s*$', na=False)
df_without_brands = df_null | df_whitespace

total_without_brands = df_without_brands.sum() 
total_with_brands = len(df_copy) - total_without_brands 
# Conteo de valores de la columna Marca que no están vacíos
brands = df_copy[~df_without_brands]['x_studio_many2many_field_37q_1irl4uc58'].value_counts()

display(Markdown("#### Diagnóstico de marcas"))
print(f"Total productos: {len(df_copy) }")
print(f"Con marca: {total_with_brands} ({total_with_brands/len(df_copy) *100:.2f}%)")
print(f"Sin marca: {total_without_brands} ({total_without_brands/len(df_copy) *100:.2f}%)")

display(Markdown("#### Estadísticas de marcas"))
print(f"Total de marcas únicas: {len(brands)}")
print(f"Marca más frecuente: {brands.index[0]} ({brands.iloc[0]} productos)")
print(f"Marca menos frecuente: {brands.index[-1]} ({brands.iloc[-1]} productos)")

# Marcas que aparecen solo una vez
one_register_brands = brands[brands == 1]
print(f"Marcas con un solo producto: {len(one_register_brands)} ({len(one_register_brands)/len(brands)*100:.2f}% del total de marcas)")

#### Diagnóstico de marcas

Total productos: 14215
Con marca: 7261 (51.08%)
Sin marca: 6954 (48.92%)

#### Estadísticas de marcas

Total de marcas únicas: 616
Marca más frecuente: POINTER (690 productos)
Marca menos frecuente: THIRD CLASSROOM (1 productos)
Marcas con un solo producto: 292 (47.40% del total de marcas)

In [91]:
""" 
Normalización de códigos de barra
Convierte código de barras a string y elimina ceros al inicio
"""
def barcode_normalization(code):
    if pd.isna(code): # Evalua si está vacío
        return None
    code = str(code).strip()
    try:
        # Esto elimina ceros al inicio automáticamente
        code = str(int(float(code)))
    except:
        pass
    return code

df_odoo['barcode_norm'] = df_odoo['barcode'].apply(barcode_normalization)
df_int['barcode_norm'] = df_int['UPC Code'].apply(barcode_normalization)

display(Markdown("#### Ejemplos de normalización"))
overview = pd.DataFrame({
    'original_odoo': df_odoo['barcode'].head(5),
    'normalizado_odoo': df_odoo['barcode_norm'].head(5),
    'original_int': df_int['UPC Code'].head(5),
    'normalizado_int': df_int['barcode_norm'].head(5)
})
display(overview)

#### Ejemplos de normalización

   original_odoo normalizado_odoo   original_int normalizado_int
0  7453066213137    7453066213137  7512155423106   7512155423106
1            NaN             None    40568000067     40568000067
2            NaN             None  7465376497664   7465376497664
3             93               93  6930180607994   6930180607994
4             17               17    60000001438     60000001438

In [92]:
# Creación de diccionario de Interfuerza: barcode_norm → Marca, tomando registros que tengan ambos campos
# dropna() elimina cualquier fila que tenga al menos un valor nulo
# subset selecciona una porción específica de un Dataframe
df_int_valids = df_int.dropna(subset=['barcode_norm', 'Marca']) 

# Eliminar duplicados de barcode normalizado
df_int_uniques = df_int_valids.drop_duplicates(subset=['barcode_norm'])

# Creación de diccionario
# Unión de 'barcode_norm' con 'Marca' en tuplas usando zip()
brands_map = dict(zip(df_int_uniques['barcode_norm'], df_int_uniques['Marca'])) 
print(f"Mapa creado con {len(brands_map)} códigos de barras únicos")

Mapa creado con 73303 códigos de barras únicos

### Identificación de códigos con múltiples marcas

In [96]:
# Agrupa los códigos df_int_valids mostrando los valores de marca por cada código
# nunique() Muestra la cantidad de marcas únicas por cada código
conflicts_per_code = df_int_valids.groupby('barcode_norm')['Marca'].nunique()
# Verificación si hay códigos con más de una marca
codes_with_conflicts = conflicts_per_code[conflicts_per_code > 1]

display(Markdown("#### Conflictos de marcas por código de barras"))

display(Markdown("\n ##### Estadísticas generales"))
print(f"Total registros en Interfuerza: {len(df_int_valids):,}")
print(f"Total códigos de barras únicos: {df_int_valids['barcode_norm'].nunique():,}")
print(f"Códigos con múltiples marcas: {len(codes_with_conflicts):,}")
print(f"Porcentaje del total: {len(codes_with_conflicts)/df_int_valids['barcode_norm'].nunique()*100:.2f}%")

display(Markdown("\n ##### Distribución de conflictos"))
print(f"Códigos con 2 marcas diferentes: {(codes_with_conflicts == 2).sum()}")
print(f"Códigos con 3 marcas diferentes: {(codes_with_conflicts == 3).sum()}")
print(f"Códigos con 4+ marcas diferentes: {(codes_with_conflicts >= 4).sum()}")

#### Conflictos de marcas por código de barras

 ##### Estadísticas generales

Total registros en Interfuerza: 73,451
Total códigos de barras únicos: 73,303
Códigos con múltiples marcas: 60
Porcentaje del total: 0.08%

 ##### Distribución de conflictos

Códigos con 2 marcas diferentes: 60
Códigos con 3 marcas diferentes: 0
Códigos con 4+ marcas diferentes: 0

### Análisis de formato para códigos con marcas múltiples

In [100]:
display(Markdown("#### Formato inicial para marcas múltiples"))

# CORRECIÓN ORIGINAL
data_brands_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'MarcasSeleccionadas.csv')
df_odoo_corrected = pd.read_csv(data_brands_path)
# iloc se utiliza para seleccionar un registro específico
display(df_odoo_corrected)

"""
Filtro con str.contains para encontrar valores con en la columna de Marca
odoo_multiples_brands = df_odoo_corrected[df_odoo_corrected['Marca'].str.contains(",", na=False)]
"""

# División de marcas múltiples para un mismo código
# Dividir valores en la columna Marca que tengan , utilizando Split y asignarlos a una nueva columna "Multiples_Brands"
df_odoo_corrected['Multiples_Brands'] = df_odoo_corrected['Marca'].str.split(",")
display(Markdown("#### Formato nuevo aplicado para marcas múltiples"))
display(df_odoo_corrected)

#### Formato inicial para marcas múltiples

,Código de barras,Nombre,Marca
0,78628923469,BORDE MURAL TIRA TREND BRIGHT BOOKS,TREND
1,805585,BROCHE 1- 1/8 X 5PQ. MARIPO 80558000059,S/M
2,60084000099,DUPLICADO BANNER FELIZ CUMPLEA?OS 060084000099,NaN
3,751214576491,ETIQUET TSUM PAQ10,"GRANMARK,DIVERTEX"
4,772024587,JUMBO PALM STAMPERS,MELISSA & DOUG
...,...,...,...
104,363330901424,PINTURA SPRAY ROJO 12/9 #9018,SPRAY BRITE
105,105949,ROMBITO TORNASOL,DAISY
106,7453008112672,ROMPECABEZA MINNIE 48PZS PISO 11267-MN,NaN
107,42229272844,SARGENT ART LAPIZ 36COLOR CAJA METAL,SARGENT ART
108,10514000083,VELA BAUTIZO/COMUNION,DAISY

#### Formato nuevo aplicado para marcas múltiples

,Código de barras,Nombre,Marca,Multiples_Brands
0,78628923469,BORDE MURAL TIRA TREND BRIGHT BOOKS,TREND,[TREND]
1,805585,BROCHE 1- 1/8 X 5PQ. MARIPO 80558000059,S/M,[S/M]
2,60084000099,DUPLICADO BANNER FELIZ CUMPLEA?OS 060084000099,NaN,NaN
3,751214576491,ETIQUET TSUM PAQ10,"GRANMARK,DIVERTEX","[GRANMARK, DIVERTEX]"
4,772024587,JUMBO PALM STAMPERS,MELISSA & DOUG,[MELISSA & DOUG]
...,...,...,...,...
104,363330901424,PINTURA SPRAY ROJO 12/9 #9018,SPRAY BRITE,[SPRAY BRITE]
105,105949,ROMBITO TORNASOL,DAISY,[DAISY]
106,7453008112672,ROMPECABEZA MINNIE 48PZS PISO 11267-MN,NaN,NaN
107,42229272844,SARGENT ART LAPIZ 36COLOR CAJA METAL,SARGENT ART,[SARGENT ART]
108,10514000083,VELA BAUTIZO/COMUNION,DAISY,[DAISY]

### Análisis de corrección de códigos con marcas múltiples

In [102]:
# CODIGOS CON CONFLICTO - INTERFUERZA 
# Identificar qué códigos se encuentran en codes_with_conflicts
df_int_conflicts = df_int_valids[df_int_valids['barcode_norm'].isin(codes_with_conflicts.index)]
# Convertir los valores de 'Marca' en String
df_int_conflicts.loc[:, 'Marca'] = df_int_conflicts['Marca'].astype(str)
# Dataframe con las columnas de código normalizado y marca. el .agg(', '.join) organiza varios valores de marca en una sola fila
df_int_grouped = df_int_conflicts.groupby('barcode_norm')['Marca'].agg(', '.join).reset_index()
display(Markdown("#### Códigos de Interfuerza"))
display(df_int_grouped.head(5))

# CÓDIGOS CORREGIDOS EN ODOO
df_odoo_corrected['barcode_norm'] = df_odoo_corrected['Código de barras'].apply(barcode_normalization)
df_odoo_corrected.loc[:, 'Marca'] = df_odoo_corrected['Marca'].astype(str)
df_odoo_grouped = df_odoo_corrected.groupby('barcode_norm')['Marca'].agg(', '.join).reset_index()
display(Markdown("#### Códigos de Odoo"))
display(df_odoo_grouped.head(5))

# BASE INICIAL DE REPORTE
# Unión de dos DataFrames
df_report = df_int_grouped.merge(
    df_odoo_grouped, 
    on='barcode_norm', # Unión en código de barras
    how='inner', # Solo conserva códigos que existen en ambos DataFrames
    suffixes=('_interfuerza', '_odoo') # Agrega el sufijo a columnas con el mismo nombre
)

# COMPARA SI HAY AL MENOS UNA MARCA QUE COINCIDA
def compare_general_brands(df_report):
    int_brands = df_report['Marca_interfuerza']
    odoo_brands = df_report['Marca_odoo']
    
    # Manejo de nulos
    if pd.isna(int_brands) or pd.isna(odoo_brands):
        return 'No'
        
    # Conversión a string
    int_brands = str(int_brands)
    odoo_list = str(odoo_brands).split(',')
    
    for brand in odoo_list:
        if brand.strip() in int_brands:
            return 'Yes'
    return 'No'

# COMPARA SI TODAS LAS MARCAS COINCIDEN
def compare_specific_brands(df_report):
    int_brands = df_report['Marca_interfuerza']
    odoo_brands = df_report['Marca_odoo']

    if pd.isna(int_brands) or pd.isna(odoo_brands):
        return 'No'

    """
        Convertir a conjunto y separar las marcas en coma para compararlas directamente
        Los conjuntos no tienen orden y no permiten duplicados
        strip() elimina espacios alrededor de cada marca
    """
    int_set = set([b.strip() for b in str(int_brands).split(',')])
    odoo_set = set([b.strip() for b in str(odoo_brands).split(',')])
    
    # Verificar si TODAS las marcas de Odoo están en Interfuerza
    return 'Yes' if int_set == odoo_set else 'No'

display(Markdown("#### Comparación de corrección de marcas"))
# Aplicar las funciones para todas las filas
df_report['Comparación General'] = df_report.apply(compare_general_brands, axis=1)
df_report['Comparación Precisa'] = df_report.apply(compare_specific_brands, axis=1)
display(df_report.head(5))

#### Códigos de Interfuerza

  barcode_norm                                Marca
0  10100001258  STARMATE,POINTER, POINTER/METACOLOR
1  10200000786                          XX, OJENISA
2  10224000052                             X, RODEO
3       104142                       OJENISA, DAISY
4       104927                        MYLIN, SEDCIN

#### Códigos de Odoo

  barcode_norm                                              Marca
0  10100001258  STARMATE/POINTER, METACOLOR,POINTER,STARMATE, ...
1  10200000786                                            OJENISA
2  10224000052                                                S/M
3       104142                                            OJENISA
4       104927                                             SEDCIN

#### Comparación de corrección de marcas

,barcode_norm,Marca_interfuerza,Marca_odoo,Comparación General,Comparación Precisa
0,10100001258,"STARMATE,POINTER, POINTER/METACOLOR","STARMATE/POINTER, METACOLOR,POINTER,STARMATE, ...",Yes,No
1,10200000786,"XX, OJENISA",OJENISA,Yes,No
2,10224000052,"X, RODEO",S/M,No,No
3,104142,"OJENISA, DAISY",OJENISA,Yes,No
4,104927,"MYLIN, SEDCIN",SEDCIN,Yes,No

### Resumen Estadístico de Resultados

In [105]:
display(Markdown("#### Estadística General"))

# TOTALES INTERFUERZA - ODOO
print(f"TOTAL DE CÓDIGOS CON CONFLICTOS: {len(codes_with_conflicts)}")

print(f"\nANTES (Interfuerza)")
print(f"Códigos con 2 marcas diferentes: {(codes_with_conflicts == 2).sum()}")
print(f"Códigos con 3 marcas diferentes: {(codes_with_conflicts == 3).sum()}")
print(f"Códigos con 4+ marcas diferentes: {(codes_with_conflicts >= 4).sum()}")

df_report['odoo_brand_count'] = df_report['Marca_odoo'].str.split(',').str.len()
print(f"\nDESPUÉS (Odoo)")
print(f"Códigos con 1 marca: {(df_report['odoo_brand_count'] == 1).sum()}")
print(f"Códigos con 2 marcas: {(df_report['odoo_brand_count'] == 2).sum()}")
print(f"Códigos con 3+ marcas: {(df_report['odoo_brand_count'] >= 3).sum()}")

# COMPARACIÓN DE MARCAS CORREGIDAS INTERFUERZA VS ODOO
print(f"\nMATCH DE MARCAS INTERFUERZA-ODOO")
print(f"Coincidencia en alguna marca: {(df_report['Comparación General'] == 'Yes').sum()} ({(df_report['Comparación General'] == 'Yes').sum()/len(df_report)*100:.1f}%)")
print(f"Concidencia en todas las marcas: {(df_report['Comparación Precisa'] == 'Yes').sum()} ({(df_report['Comparación Precisa'] == 'Yes').sum()/len(df_report)*100:.1f}%)")

resolved = ((df_report['Marca_interfuerza'].str.split(',').str.len()) > 1) & (df_report['odoo_brand_count'] == 1)
partial = (df_report['odoo_brand_count'] > 1)
no_coincidence = (df_report['Comparación General'] == 'No')

display(Markdown("#### Resumen de acciones y resultados"))
print(f"""Un total de {len(codes_with_conflicts)} códigos de barra estaban duplicados, resultando en multiple marcas que fueron identificados en Interfuerza.

ACCIONES TOMADAS:
- Cada uno de los {len(codes_with_conflicts)} casos fue manualmente revisado en Odoo.
- Muchos códigos eran duplicados con marcas erróneas (mal escritas, inexistentes, desfasadas, etc).
- Para productos diferentes con el mismo código se decició en base de la activadad del producto. 

RESULTADOS:
- ✅ {resolved.sum()} códigos ({resolved.sum()/len(df_report)*100:.1f}%) fueron simplificados a una sola marca
- ✅ {partial.sum()} códigos ({partial.sum()/len(df_report)*100:.1f}%) mantienen más de una marca
- ❌ {no_coincidence.sum()} códigos ({no_coincidence.sum()/len(df_report)*100:.1f}%) no tienen coincidencia con Interfuerza
""")

#### Estadística General

TOTAL DE CÓDIGOS CON CONFLICTOS: 60

ANTES (Interfuerza)
Códigos con 2 marcas diferentes: 60
Códigos con 3 marcas diferentes: 0
Códigos con 4+ marcas diferentes: 0

DESPUÉS (Odoo)
Códigos con 1 marca: 50
Códigos con 2 marcas: 8
Códigos con 3+ marcas: 1

MATCH DE MARCAS INTERFUERZA-ODOO
Coincidencia en alguna marca: 44 (74.6%)
Concidencia en todas las marcas: 5 (8.5%)

#### Resumen de acciones y resultados

Un total de 60 códigos de barra estaban duplicados, resultando en multiple marcas que fueron identificados en Interfuerza.

ACCIONES TOMADAS:
- Cada uno de los 60 casos fue manualmente revisado en Odoo.
- Muchos códigos eran duplicados con marcas erróneas (mal escritas, inexistentes, desfasadas, etc).
- Para productos diferentes con el mismo código se decició en base de la activadad del producto.

RESULTADOS:
- ✅ 50 códigos (84.7%) fueron simplificados a una sola marca
- ✅ 9 códigos (15.3%) mantienen más de una marca
- ❌ 15 códigos (25.4%) no tienen coincidencia con Interfuerza

### Identificación y creación de marcas no existentes en Odoo

In [112]:
assigned_brands = df_odoo_brands_import['x_studio_many2many_field_37q_1irl4uc58'].unique()
print(f"Cantidad de marcas únicas por asignar a productos sin marca en Odoo: {len(assigned_brands)}")

data_odoo_brands_path = os.path.join(notebook_dir, '..', 'data', 'raw', 'MarcasOdoo.csv')
df_odoo_brands = pd.read_csv(data_odoo_brands_path)
print(f"Marcas existentes en Odoo: {len(df_odoo_brands)}")
display(Markdown("#### Muestra de marcas existentes"))
display(df_odoo_brands.head())

# IDENTIFICACIÓN DE MARCAS FALTANTES EN ODOO
odoo_brands_standardized = set(
    df_odoo_brands['name'].astype(str).str.strip().str.lower()
)

# Encontrar marcas que no existen en Odoo
new_odoo_brands = []
for brand in assigned_brands:
    brand_str = str(brand).strip()
    if brand_str.lower() not in odoo_brands_standardized:
        new_odoo_brands.append(brand_str)

# Eliminar duplicados por si el mismo nombre aparece varias veces
new_odoo_brands = list(set(new_odoo_brands))

display(Markdown("##### Muestra de marcas nuevas"))
print(f"Marcas nuevas a crear: {len(new_odoo_brands)}")
display(new_odoo_brands[:5])

df_new_odoo_brands = pd.DataFrame({
    'name': new_odoo_brands
})

data_new_odoo_brands_path = os.path.join(notebook_dir, '..', 'data', 'processed', 'MarcasNuevasOdoo.csv')
df_new_odoo_brands.to_csv(data_new_odoo_brands_path, index=False)
print("\nArchivo 'MarcasNuevasOdoo.csv' generado")
print(f"Contiene {len(df_new_odoo_brands)} marcas para crear en Odoo")

Cantidad de marcas únicas por asignar a productos sin marca en Odoo: 946
Marcas existentes en Odoo: 1691

#### Muestra de marcas existentes

                                  id    name
0  __export__.product_tag_2_53e61365  Corsel
1  __export__.product_tag_3_a1f95b5d  Direct
2  __export__.product_tag_4_9ac42890    BODA
3  __export__.product_tag_5_b39c9e2f     S/M
4  __export__.product_tag_6_5cefcf1f     DFH

##### Muestra de marcas nuevas

Marcas nuevas a crear: 645

["MOMENT'S", 'EMSAMBLE/BASH', 'PUSH TOY', 'GUTTEMAN', 'ORNAMENTS']

Archivo 'MarcasNuevasOdoo.csv' generado
Contiene 645 marcas para crear en Odoo

### Asignación de marcas a productos sin marca

In [107]:
# Productos sin marca
df_without_brand = df_odoo[df_without_brands].copy()
# Excluir los que tienen código en codes_with_conflicts
df_without_brand = df_without_brand[~df_without_brand['barcode_norm'].isin(codes_with_conflicts.index)]

display(Markdown("#### Análisis de productos sin marca"))
print(f"Productos sin marca: {len(df_odoo[df_without_brands])}")
print(f"Productos sin marca excluyendo códigos corregidos: {len(df_without_brand)}")

# Aplicación de mapa de marcas de Interfuerza
df_without_brand['marca_asignada'] = df_without_brand['barcode_norm'].map(brands_map)

assigned = df_without_brand['marca_asignada'].notna().sum()
total_pendings = len(df_without_brand) - assigned
pendings = df_without_brand[df_without_brand['marca_asignada'].isna()]
print(f"✅ Resueltos automáticamente: {assigned} ({assigned/len(df_without_brand)*100:.1f}%)")
print(f"❌ Pendientes (sin coincidencia): {total_pendings} ({total_pendings/len(df_without_brand)*100:.1f}%)\n")

display(Markdown("\n#### MUESTRA DE PRODUCTOS SIN MARCA"))
display(pendings)
print("\n")

# Guardado de archivo con marcas asignadas listo para importación en Odoo
df_odoo_brands_import = df_without_brand[df_without_brand['marca_asignada'].notna()].copy()
df_odoo_brands_import = df_odoo_brands_import[['id', 'marca_asignada']]
df_odoo_brands_import.columns = ['id', 'x_studio_many2many_field_37q_1irl4uc58']

data_odoo_missing_brands_path = os.path.join(notebook_dir, '..', 'data', 'processed', 'MarcasParaActualizar.csv')
df_odoo_brands_import.to_csv(data_odoo_missing_brands_path, index=False)
display(Markdown("##### Archivo 'MarcasParaActualizar.csv' generado"))

#### Análisis de productos sin marca

Productos sin marca: 6954
Productos sin marca excluyendo códigos corregidos: 6954
✅ Resueltos automáticamente: 6136 (88.2%)
❌ Pendientes (sin coincidencia): 818 (11.8%)

#### MUESTRA DE PRODUCTOS SIN MARCA

,id,name,barcode,default_code,x_studio_many2many_field_37q_1irl4uc58,categ_id,seller_ids,barcode_norm,marca_asignada
1,__export__.product_template_219315_4256fd8c,ARCHIVADOR VERTICAL 3 GAVETAS Y CERRADURA,NaN,NaN,NaN,All,NaN,None,NaN
2,__export__.product_template_219316_dfced89f,ARCHIVADOR VERTICAL 4 GAVETAS Y CERRADURA,NaN,NaN,NaN,All,NaN,None,NaN
7,__export__.product_template_219323_100f066b,BATERIA PARA MAQUINA SOPLADORA DE 20 V,NaN,NaN,NaN,All,NaN,None,NaN
8,__export__.product_template_219265_00222d80,CADENA STRASS 3 LINEAS C/PIEDRA X YDA,109223,CL:8168-10YD,NaN,Sedería / Cintas,MEGA ENSAMBLES INT S.A.,109223,NaN
9,__export__.product_template_219266_6f6f9bfc,CADENA STRASS SS6 PLATEADO X YDA,109225,CL:SLV-6-SS6,NaN,Sedería / Cintas,NaN,109225,NaN
...,...,...,...,...,...,...,...,...,...
14209,__export__.product_template_218990_b0e13086,[US0510] SILLA EJECUTIVA BLACK,NaN,NaN,NaN,All,NaN,None,NaN
14210,__export__.product_template_220006_59c1bc27,boligrafo,NaN,NaN,NaN,All,NaN,None,NaN
14211,__export__.product_template_220042_92eb42f0,http://www.iamstarmate.com,NaN,NaN,NaN,All,NaN,None,NaN
14212,__export__.product_template_220041_6b35324e,https://facela.com/,NaN,NaN,NaN,All,NaN,None,NaN
14213,__export__.product_template_219991_49f2d6bc,httpÑ--l.ead.me-bawcfi,NaN,NaN,NaN,All,NaN,None,NaN

##### Archivo 'MarcasParaActualizar.csv' generado